### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/1022-practices#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create an HTML skeleton for the page
- [x] set the background to a color
- [x] set the car and size it
